### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-luminosity#2]
Very nice!

in 01 https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/01-introduction/index.html

- [x] add a link to the portal instructions http://opendata.cern.ch/docs/cms-guide-luminosity-calculation (here or maybe in later episodes?)

in 02 https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/02-installing-brilcalc/index.html:

- [x] add a link to the docker cvmfs install instructions in `[the cvmfs file system installed](https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/04-cvmfs-and-brilcalc/index.html)`

in 03 https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/03-calculating-luminosity/index.html:

- [x] add a link to the portal records and instruct how to find them, .e.g. something like "...runs is provided in the form of a JSON file. You can find the list of certified data on the CERN Open data portal with [this search](http://opendata.cern.ch/search?page=1&size=20&q=&experiment=CMS&subtype=Validation&type=Supplementaries&type=Environment) and each data record has a link to the corresponding JSON file.

- [x] add a mention where to find the data range for the "Luminosity over a range of runs" exercise. It is written in each PD record.

- [x] is the column `source` and output `hfoc` explained somewhere. There's a good concise explanation in the portal records such as http://opendata.cern.ch/record/1053

**Comment by tpmccauley** [comment]
> Very nice!
> 
> in 01 https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/01-introduction/index.html
> 
>     * [ ]  add a link to the portal instructions http://opendata.cern.ch/docs/cms-guide-luminosity-calculation (here or maybe in later episodes?)
> 

This is in under "Further information" in the Reference section
> 
> in 02 https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/02-installing-brilcalc/index.html:
> 
>     * [ ]  add a link to the docker cvmfs install instructions in `[the cvmfs file system installed](https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/04-cvmfs-and-brilcalc/index.html)`
> 
This is referenced and linked in Setup

> 
> in 03 https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/03-calculating-luminosity/index.html:
> 
>     * [ ]  add a link to the portal records and instruct how to find them, .e.g. something like "...runs is provided in the form of a JSON file. You can find the list of certified data on the CERN Open data portal with [this search](http://opendata.cern.ch/search?page=1&size=20&q=&experiment=CMS&subtype=Validation&type=Supplementaries&type=Environment) and each data record has a link to the corresponding JSON file.
> 
Done

>     * [ ]  add a mention where to find the data range for the "Luminosity over a range of runs" exercise. It is written in each PD record.
Done

> 
>     * [ ]  is the column `source` and output `hfoc` explained somewhere. There's a good concise explanation in the portal records such as http://opendata.cern.ch/record/1053

Added just below it

**Comment by katilp** [comment]
Where's the reference section?

**Comment by tpmccauley** [comment]
Under Extras
https://cms-opendata-workshop.github.io/workshop-lesson-luminosity/reference.html

**Comment by katilp** [comment]
oh, that's hard to find (... well it is very visible once you say it.. ) Maybe an additional link to it somewhere. I have not seen it used (or realized that it has been used) in other lessons.

**Comment by tpmccauley** [comment]
I added it to the bottom of the last episode
