### ISSUE TITLE
Orphan LS and data quality

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop-lesson-luminosity#3]
Thanks Tom, very nice!
Along the lines of what Kati already pointed out.  Maybe a word on the orphan lumi sections could be of help.  They are briefly described at: http://opendata-dev.web.cern.ch/record/1054

Will you be emphasizing in the video the usage of json files for data quality.  At that point, they will quite familiar with cmssw config files, so nothing fancy should be said, just maybe present they way the data quality file is loaded.

**Comment by tpmccauley** [comment]
> Thanks Tom, very nice!
> Along the lines of what Kati already pointed out. Maybe a word on the orphan lumi sections could be of help. They are briefly described at: http://opendata-dev.web.cern.ch/record/1054
> 
Will do

> Will you be emphasizing in the video the usage of json files for data quality. At that point, they will quite familiar with cmssw config files, so nothing fancy should be said, just maybe present they way the data quality file is loaded.

Do you mean in a cfg.py file?

**Comment by caredg** [comment]
Yes, just the lines that will load the file.  And maybe mention what the numbers inside the json mean.
